[package]
name = "koala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
num = "0.4.2"
sysinfo = "0.29.10"
